[package]
name = "rust-ray-tracing-demo"
version = "0.1.0"
authors = ["yj_gu <yj_gu@ctrip.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
